---
# chevereto
- name: download Docker installation script
  get_url:
    url: "https://chevereto.com/sh/ubuntu/22.04/docker.sh"
    dest: "/home/{{ username }}/docker.sh"
#  become: true
 # become_user: "{{ username }}"

- name: set execute permissions on the script
  file:
    path: "/home/{{ username }}/docker.sh"
    mode: "u+x"

- name: run the Docker installation script
  shell: "./docker.sh"
  args:
    chdir: "/home/{{ username }}"
 # become: true

- name: config file setup
  template:
    src: env.j2
    dest: "/home/{{ username }}/docker/.env" 

#- name: run setup
#  make:
#    chdir: "/home/{{ username }}/docker"
#    target: setup
 # become: true
 #become_user: "{{ username }}"

- name: Run 'make setup'
  command: "make setup"
  args:
   chdir: "/home/{{ username }}/docker"
  become: true
  ignore_errors: yes
#  become_user: "{{ username }}"

- name: run image
  make:
    chdir: "/home/{{ username }}/docker"
    target: image
 # become: true
 # become_user: "{{ username }}"

- name: run deploy
  make:
    chdir: "/home/{{ username }}/docker"
    target: "deploy NAMESPACE=demo ADMIN_EMAIL={{ soa_email_address }}"
 # become: true
 # become_user: "{{ username }}"
  register: make_deploy_result

#- name: Run 'make deploy'
#  command: "make deploy NAMESPACE=demo ADMIN_EMAIL={{ soa_email_address }}"
#  args:
#    chdir: "/home/{{ username }}/docker"
#  become: true
#  become_user: "{{ username }}"
#  register: make_deploy_result

- name: Parse Email and Password from make deploy output
  set_fact:
    chevereto_email: "{{ make_deploy_result.stdout_lines | regex_search('Email: (.*)', '\\1') }}"
    chevereto_password: "{{ make_deploy_result.stdout_lines | regex_search('Password: (.*)', '\\1') }}"

- name: recursively change ownership 
  file:
    path: "/home/{{ username }}/docker"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    state: directory
  become: yes