---
- name: Install passlib library for htpasswd generation
  pip:
  name: passlib
  state: present

- name: Create htpasswd file for wizard protection
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd_wizard
    name: onlyoffice
    password: "{{ wizard_password }}"
    mode: '0640'

- name: Enable HTTP Basic Auth in DocSpace Nginx router
  blockinfile:
    path: /app/onlyoffice/router/conf/onlyoffice-docspace.conf
    marker: "# {mark} ANSIBLE WIZARD AUTH"
    insertafter: "location / {"
    block: |
      auth_basic "Restricted Setup Wizard";
      auth_basic_user_file /etc/nginx/.htpasswd_wizard;

- name: Reload Nginx router container to enforce basic auth
  command: docker exec docspace-router nginx -s reload
  changed_when: true
