# FileCloud installation
- name: Adding Keys for MongoDB
  get_url:
      url: https://pgp.mongodb.com/server-6.0.asc
      dest: /usr/share/keyrings/mongodb-server-6.0.asc
      mode: '0644'
      force: true 

- name: adding mongodb repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.asc ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
    state: present

- name: Adding Keys for FileCloud
  get_url:
      url: https://repo.filecloudlabs.com/static/pgp/filecloud.asc
      dest: /usr/share/keyrings/filecloud.asc
      mode: '0644'
      force: true

- name: adding filecloud repo
  apt_repository:
    repo: "deb [ arch=amd64 signed-by=/usr/share/keyrings/filecloud.asc ] https://repo.filecloudlabs.com/apt/ubuntu jammy/filecloud/23.232 main"
    state: present

- name: running apt-get update
  apt:
    update_cache: yes
    upgrade: yes

- name: Installing the Apache and MongoDB servers.
  apt:
    name:
    - apache2
    - mongodb-org
    - pigz
    state: present

- name: Installing PHP 8.2 and dependencies
  apt:
    name: php8.2*
    install_recommends: no
    state: present

- name: Installing FileCloud! :)
  apt:
    name: filecloud
    state: present

# reset admin password
- name: run PHP script to reset admin password
  command: 'php resetadminpw.php -p "{{ filecloud_admin_password }}"'
  args:
    chdir: '/var/www/html/resources/backup/'

# configure filecloud
- name: logging into filecloud
  uri:
    url: http://{{ ansible_default_ipv4.address }}/admin/adminlogin?adminuser=admin&adminpassword={{ filecloud_admin_password }}
    method: POST
    body_format: form-urlencoded
    status_code: 200
    force_basic_auth: yes
  register: login_cookies

- name: saving cookies to variable
  set_fact:
    login: "{{ login_cookies.cookies }}"

- name: extracting tonidocloud_ah value
  set_fact:
    tonidocloud_ah: "{{ login['tonidocloud-ah'] }}"

- name: extracting tonidocloud_as value
  set_fact:
    tonidocloud_as: "{{ login['tonidocloud-as'] }}"

- name: extracting x_xsrf_token value
  set_fact:
    x_xsrf_token: "{{ login['X-XSRF-TOKEN'] }}"

- name: configuring GEO IP
  uri:
    url: http://{{ ansible_default_ipv4.address }}/admin/
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
      Cookie: X-XSRF-TOKEN-admin={{ x_xsrf_token }}; X-XSRF-TOKEN={{ x_xsrf_token }}; tonidocloud-au=admin; tonidocloud-as={{ tonidocloud_as }}; tonidocloud-ah={{ tonidocloud_ah }}; tonidocloud-ah={{ tonidocloud_ah }}; tonidocloud-as={{ tonidocloud_as }}; tonidocloud-au=admin
    body_format: form-urlencoded
    body:
      op: "setconfigsetting"
      count: "1"
      param0: "TONIDOCLOUD_GEOIP_ENABLED"
      value0: "1"

# solr
- name: installing solr
  command: filecloudcp -s

- name: copying fcskel into dest
  copy:
    src: /var/www/html/thirdparty/overrides/solarium/Solarium/fcskel
    dest: /opt/solrfcdata/var/solr/data/
    recurse: yes

- name: changing owner of fccore
  file:
    path: /opt/solrfcdata/var/solr/data/fccore
    owner: solr
    state: directory
    recurse: yes

- name: Configuring Solr
  uri:
    url: http://{{ ansible_default_ipv4.address }}/admin/confcreate
    method: POST
    headers:
      Cookie: X-XSRF-TOKEN={{ x_xsrf_token }}; X-XSRF-TOKEN-admin={{ x_xsrf_token }}; tonidocloud-ah={{ tonidocloud_ah }}; tonidocloud-as={{ tonidocloud_as }}; tonidocloud-au=admin
    body_format: form-urlencoded
    force_basic_auth: yes

# Apache ssl
- name: stop apache2
  systemd:
    name: apache2
    state: stopped

- name: setting up ssl certificate
  import_role:
    name: certbot_ssl

- name: moving vhost template
  template:
    src: templates/vhost.j2
    dest: "/etc/apache2/sites-available/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: symlinking our vhost
  file:
    src: "/etc/apache2/sites-available/{{ _domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644
    state: link

- name: disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: start apache2
   

