---
- name: restart openfang
  systemd_service:
    name: openfang
    state: restarted

- name: daemon reload
  systemd_service:
    daemon_reload: true

- name: restart nginx
  systemd_service:
    name: nginx
    state: restarted

