---
- name: Create Milvus directory
  file:
    path: /opt/milvus
    state: directory
    mode: "0755"

- name: Deploy docker-compose.yml
  template:
    src: cpu-docker-compose.yml.j2
    dest: /opt/milvus/docker-compose.yml
    mode: "0644"

- name: Ensure Milvus is running
  community.docker.docker_compose_v2:
    project_src: /opt/milvus
    state: started