---
# antmedia

- name: set facts for Community edition
  set_fact:
    ant_media_install_script_url: 'https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh'
    ant_media_zip_remote_url: 'https://antmedia.io/download/latest.zip'
    ant_media_zip_local_path: '/tmp/ams.zip'
  when: version == 'Community'

- name: set facts for Community edition
  set_fact:
    ant_media_install_script_url: 'https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh'
    ant_media_zip_remote_url: 'https://antmedia.io/linode/antmedia_2.5.3.zip'
    ant_media_zip_local_path: '/tmp/ams.zip'
  when: version == 'Enterprise'

- name: download install_ant-media-server.sh script
  get_url:
    url: "{{ ant_media_install_script_url }}"
    dest: "/tmp/install_ant-media-server.sh"
    mode: '0755'

- name: download ams.zip file from a remote location
  get_url:
    url: "{{ ant_media_zip_remote_url }}"
    dest: "{{ ant_media_zip_local_path }}"

- name: run Ant Media Server installation script
  command: "/tmp/install_ant-media-server.sh -i {{ ant_media_zip_local_path }}"

# ssl_certbot
- name: setting up ssl certificate
  import_role:
    name: certbot_ssl

- name: set facts for letsencrypt certs
  set_fact:
    full: "/etc/letsencrypt/live/{{ _domain }}/fullchain.pem"
    priv: "/etc/letsencrypt/live/{{ _domain }}/privkey.pem"
    chain: "/etc/letsencrypt/live/{{ _domain }}/chain.pem"

# AMS ssl install script
  command: ./enable_ssl.sh -f {{ full }} -p {{ priv }} -c {{ chain }} -d {{ _domain }}
  args:
    chdir: /usr/local/antmedia






