---
# user creation
- name: creating mongo root user
  community.mongodb.mongodb_user:
    database: admin
    name: mongo-root
    password: "{{ mongo_root_password }}"
    roles: root 
    state: present

- name: creating mongo admin user
  community.mongodb.mongodb_user:
    database: admin
    name: mongo-admin
    password: "{{ mongo_admin_pass }}"
    roles: userAdminAnyDatabase
    state: present