---
# add repo
- name: get rabbitmq latest signing keys release
  uri:
    url: https://api.github.com/repos/rabbitmq/signing-keys/releases/latest
    return_content: true
    status_code: 200
    body_format: json
  register: latest_release

- name: set rabbitmq assets list
  set_fact:
    rabbitmq_assets: "{{ latest_release.json.assets }}"

- name: set erlang url
  set_fact:
    erlang_url: "{{ item.browser_download_url }}"
  loop: "{{ rabbitmq_assets }}"
  when: item.browser_download_url is search('cloudsmith.rabbitmq-erlang.[A-Z0-9]+.key$')

- name: set server url
  set_fact:
    server_url: "{{ item.browser_download_url }}"
  loop: "{{ rabbitmq_assets }}"
  when: item.browser_download_url is search('cloudsmith.rabbitmq-server.[A-Z0-9]+.key$')

- name: set key ids
  set_fact:
    erlang_keyid: "{{ erlang_url | regex_search('[A-Z0-9]+\\.key$') | replace('.key', '.gpg') }}"
    server_keyid: "{{ server_url | regex_search('[A-Z0-9]+\\.key$') | replace('.key', '.gpg') }}"

- name: ensure keyrings directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: download rabbitmq erlang key
  get_url:
    url: "{{ erlang_url }}"
    dest: "/tmp/rabbitmq-erlang.asc"
    mode: '0644'

- name: dearmor erlang key
  command:
    cmd: >
      gpg --dearmor
      --yes
      --output /usr/share/keyrings/rabbitmq.{{ erlang_keyid }}
      /tmp/rabbitmq-erlang.asc
  args:
    creates: "/usr/share/keyrings/rabbitmq.{{ erlang_keyid }}"

- name: download rabbitmq server key
  get_url:
    url: "{{ server_url }}"
    dest: "/tmp/rabbitmq-server.asc"
    mode: '0644'

- name: dearmor server key
  command:
    cmd: >
      gpg --dearmor
      --yes
      --output /usr/share/keyrings/rabbitmq.{{ server_keyid }}
      /tmp/rabbitmq-server.asc
  args:
    creates: "/usr/share/keyrings/rabbitmq.{{ server_keyid }}"

- name: set distro release codename
  set_fact:
    distribution_release: "{{ ansible_facts['lsb']['codename'] }}"

- name: add rabbitmq apt repository
  copy:
    dest: /etc/apt/sources.list.d/rabbitmq.list
    content: |
      ## RabbitMQ Erlang
      deb [signed-by=/usr/share/keyrings/rabbitmq.{{ erlang_keyid }}] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ distribution_release }} main

      ## RabbitMQ Server
      deb [signed-by=/usr/share/keyrings/rabbitmq.{{ server_keyid }}] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ distribution_release }} main
    owner: root
    group: root
    mode: '0644'