# MySQL/MariaDB
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  tasks:
    # generate creds
    - name: generating sudo user and password 
      import_tasks: ../linode_helpers/roles/sudouser/tasks/main.yml
    
    - name: writing passwords to vars
      blockinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        block: | 
          db_user_password: {{ lookup('password', '/dev/null length=35 chars=ascii_letters,digits') }}
          mysql_root_password: {{ lookup('password', '/dev/null length=35 chars=ascii_letters,digits') }}


