---
# install system packages

- name: download aapanel install script using curl
  get_url:
    url: "{{ aapanel_script_url }}"
    dest: "/tmp/install_7.0_en.sh"
    mode: '0755'

#- name: Execute aaPanel install script with expect
#  expect:
#    command: /tmp/install_7.0_en.sh aapanel
#    responses:
#      "Do you want to install aaPanel to the /www directory now\\?\\(y/n\\):": "y"
#  timeout: 00
#  register: aapanel_install

- name: install aaPanel using shell with echo
  shell: echo "y" | /tmp/install_7.0_en.sh aapanel
  register: aapanel_install

- name: Gather deployment details safely
  set_fact:
    aapanel_internal_url: "{{ (aapanel_install.stdout | regex_findall('aaPanel Internal Address: (https://[0-9\\.]+:[0-9]+/\\S+)')) | default([], true) | first | default('') }}"
    aapanel_username: "{{ (aapanel_install.stdout | regex_findall('Username: (\\S+)')) | default([], true) | first | default('') }}"
    aapanel_password: "{{ (aapanel_install.stdout | regex_findall('Password: (\\S+)')) | default([], true) | first | default('') }}"
