---
# install system packages

- name: download aapanel install script using curl
  get_url:
    url: "{{ aapanel_script_url }}"
    dest: "/tmp/install_7.0_en.sh"
    mode: '0755'

#- name: Execute aaPanel install script with expect
#  expect:
#    command: /tmp/install_7.0_en.sh aapanel
#    responses:
#      "Do you want to install aaPanel to the /www directory now\\?\\(y/n\\):": "y"
#  timeout: 00
#  register: aapanel_install

- name: Run aaPanel installation with echo in shell module
  shell: echo "y" | /tmp/install_7.0_en.sh aapanel | tee /tmp/aapanel_install.log
  register: aapanel_install
  failed_when: aapanel_install.rc != 0

- name: Wait for installation to complete (if necessary)
  wait_for:
    path: /tmp/aapanel_install.log
    state: file
    timeout: 300
  when: aapanel_install.rc == 0

- name: gather deployment details
  set_fact:
    aapanel_internal_url: "{{ (aapanel_install.stdout | regex_findall('aaPanel Internal Address: (https://[0-9\\.]+:[0-9]+/\\S+)')) | default([], true) | first | default('') }}"
    aapanel_username: "{{ (aapanel_install.stdout | regex_findall('username:\\s*(\\S+)') | first | default('') }}"
    aapanel_password: "{{ (aapanel_install.stdout | regex_findall('password:\\s*(\\S+)') | first | default('') }}"
