---
# install system packages

- name: download aapanel install script using curl
  get_url:
    url: "{{ aapanel_script_url }}"
    dest: "/tmp/install_7.0_en.sh"
    mode: '0755'

- name: Execute aaPanel install script with expect
  expect:
    command: /bin/bash /tmp/install_7.0_en.sh aapanel
    responses:
      "Do you want to install aaPanel to the /www directory now\\?\\(y/n\\):": "y"
  timeout: 300
  register: aapanel_install

- name: gather deployment details
  set_fact:
    aapanel_internal_url: "{{ aapanel_install.stdout | regex_findall('aaPanel Internal Address: (https://[0-9\\.]+:[0-9]+/\\S+)') | first }}"
    aapanel_username: "{{ aapanel_install.stdout | regex_findall('Username: (\\S+)') | first }}"
    aapanel_password: "{{ aapanel_install.stdout | regex_findall('Password: (\\S+)') | first }}"