# mastodon
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  tasks:
  # generate creds
    - name: generate db password
      set_fact:
        psql_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

    - name: writing psql_password to vars
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: | 
          psql_password: {{ psql_password }}