---
- name: Create addons.sh if add_ons is not none
  copy:
    dest: /etc/profile.d/addons.sh
    content: |
      #!/bin/bash
      LOG_FILE="/var/log/marketplace_addons.log"
      ### Addon scripts go below ###
    owner: root
    group: root
    mode: '0755'
  when: add_ons is defined and add_ons != 'none'

- name: Install add-ons
  include_tasks: "{{ item.file }}"
  loop:
    - { name: "newrelic", file: "newrelic.yml" }
    - { name: "node_exporter", file: "node-exporter.yml" }
    - { name: "mysqld_exporter", file: "mysqld-exporter.yml" }
  when: item.name in add_ons

- name: Append cleanup snippet to addons.sh
  blockinfile:
    path: /etc/profile.d/addons.sh
    block: |
      # Cleanup: remove this install script
      rm -f "$SCRIPT_FILE"
      echo "$(date) - Installation script removed." | tee -a "$LOG_FILE"
    create: yes
    owner: root
    group: root
    mode: '0755'
  when: add_ons is defined and add_ons != 'none'
