---
- name: Create addons.sh
  template:
    src: 'templates/addons.sh.j2' 
    dest: '/etc/profile.d/addons.sh'
    owner: root
    group: root
    mode: 0755
  when: add_ons is defined and add_ons != 'none'

- name: Install add-ons
  include_tasks: "{{ item.file }}"
  loop:
    - { name: "newrelic", file: "newrelic.yml" }
    - { name: "node_exporter", file: "node-exporter.yml" }
    - { name: "mysqld_exporter", file: "mysqld-exporter.yml" }
  when: item.name in add_ons

