---
- name: install newrelic
  include_tasks:
    file: newrelic.yml
  loop: "{{ add_ons }}"
  loop_control:
    index_var: count
  when: add_ons[count] == 'newrelic'

- name: install prometheus node_exporter
  include_tasks:
    file: node-exporter.yml
  loop: "{{ add_ons }}"
  loop_control:
    index_var: count
  when: add_ons[count] == 'node_exporter'

- name: install prometheus mysqld_exporter
  include_tasks:
    file: mysqld-exporter.yml
  loop: "{{ add_ons }}"
  loop_control:
    index_var: count
  when: add_ons[count] == 'mysqld_exporter'

