---
 # cyberpanel tasks as block
 # cyberpanel scripts want to be ran in /root/
- name: download cyberpanel install script
  get_url:
    url: https://cyberpanel.net/install.sh
    dest: /root/install.sh
    mode: '0755'

- name: run the install script with inputs
  shell: printf "%s\n" 1 1 | bash /root/install.sh

- name: clean up installation files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/cyberpanel.sh
    - /root/install.sh

- name: set random admin password
  command: "adminPass {{ admin_password }}"