---
# - name: Run airflow-cli to list config
#   community.docker.docker_compose:
#     project_src: /opt/airflow
#     files:
#       - docker-compose.yml
#     services:
#       - airflow-cli
#     command: airflow config list
#     state: present
#   become: yes
#   become_user: airflow

# - name: Run Airflow init container using Docker Compose
#   community.docker.docker_compose:
#     project_src: /opt/airflow
#     files:
#       - docker-compose.yml
#     services:
#       - airflow-init
#     state: present
#     restarted: yes
#   become: yes
#   become_user: airflow

- name: Ensure /opt/airflow is owned by airflow
  file:
    path: /opt/airflow
    state: directory
    recurse: yes
    owner: airflow
    group: airflow

- name: Run airflow-cli to list config
  command:
    cmd: docker compose run airflow-cli airflow config list
    chdir: /opt/airflow
  become: yes

- name: Run Airflow init container using Docker Compose
  command:
    cmd: docker compose up airflow-init
    chdir: /opt/airflow
  become: yes

- name: Update Airflow DB user password inside Postgres container
  community.docker.docker_container:
    name: airflow-postgres-password-reset
    image: postgres:15 
    command: >
      psql -h postgres -U airflow -d airflow
      -c "ALTER USER airflow WITH PASSWORD '{{ postgres_password }}';"
    env:
      PGPASSWORD: airflow  
    network_mode: "container:postgres" 
    auto_remove: true
    detach: false
  become: yes

- name: Start Airflow stack with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/airflow
    state: present
    recreate: always           # was 'yes'
    remove_orphans: true       # string lowercase true
  become: yes

# - name: Airflow Service file
#   template:
#     src: airflow.service.j2
#     dest: /etc/systemd/system/airflow.service

# - name: Restart Airflow Service
#   systemd:
#     name: airflow
#     state: started
#     enabled: true
#     daemon_reload: true