---
- name: Run airflow-cli to list config
  community.docker.docker_compose:
    project_src: /opt/airflow
    files:
      - docker-compose.yml
    services:
      - airflow-cli
    command: airflow config list
    state: present
  become: yes
  become_user: airflow

- name: Run Airflow init container using Docker Compose
  community.docker.docker_compose:
    project_src: /opt/airflow
    files:
      - docker-compose.yml
    services:
      - airflow-init
    state: present
    restarted: yes
  become: yes
  become_user: airflow

- name: Airflow Service file
  template:
    src: airflow.service.j2
    dest: /etc/systemd/system/airflow.service

- name: Restart Airflow Service
  systemd:
    name: airflow
    state: started
    enabled: true
    daemon_reload: true