# django
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  tasks:
    # generate creds
    - name: generating sudo user and password 
      import_tasks: ../linode_helpers/roles/sudouser/tasks/main.yml
      
    - name: generating passwords
      set_fact:
        POSTGRES_DB_PASSWORD: "{{ lookup('password', '/dev/null length=45 chars=ascii_letters,digits') }}"
        DJANGO_PASSWORD: "{{ lookup('password', '/dev/null length=45 chars=ascii_letters,digits') }}"

    - name: writing passwords to vars
      blockinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        block: | 
          postgres_db_pass: {{ POSTGRES_DB_PASSWORD }}
          django_password: {{ DJANGO_PASSWORD }}
