---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Create Nginx vhost configuration
  template:
    src: nginx-openfang.conf.j2
    dest: /etc/nginx/sites-available/{{ _domain }}
    mode: '0644'

- name: Add OpenFang htpasswd to protect dashboard
  copy:
    content: "{{ openfang_htpasswd_user }}:{{ openfang_htpasswd }}\n"
    dest: "{{ openfang_htpasswd_file }}"
    mode: '0640'
    owner: root
    group: www-data

- name: Enable vhost for {{ _domain }}
  file:
    src: /etc/nginx/sites-available/{{ _domain }}
    dest: /etc/nginx/sites-enabled/{{ _domain }}
    state: link

- name: Disable Nginx default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable and start Nginx
  systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Install SSL certificate
  import_role:
    name: certbot_ssl
  vars:
    webserver_stack: lemp
  notify: Restart nginx
