---
# install system packages
- name: install required dependencies
  apt:
    name:
      - curl
      - sudo
      - git
    state: present

#- name: install pihole
#  shell: curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
#  async: 500
#  poll: 25

- name: download pihole install
  get_url:
    url: https://install.pi-hole.net
    dest: "/tmp/pihole.sh"
    mode: '0755'
    
- name: download pihole
  shell: bash /tmp/pihole.sh /dev/stdin --unattended > tee /tmp/pihole.log

#- name: download pi-hole installation script
#  get_url:
#    url: https://install.pi-hole.net
#    dest: /tmp/install-pihole.sh
#    mode: '0755'

#- name: run pi-hole installer in background
#  shell: /tmp/install-pihole.sh --unattended
#  async: 500  
#  poll: 0  

- name: wait for port 80
  wait_for:
    port: 80
    delay: 5
    timeout: 600

- name: update config to listen on 8080/8443
  replace:
    path: /etc/pihole/pihole.toml
    regexp: 'port = "80o,443os,\[::\]:80o,\[::\]:443os"'
    replace: 'port = "8080o,[::]:8080o"'

- name: reconfig pihole
  command: pihole -r

