---
# mysql_secure_installation (syntax for mariadb, deb11)

- name: update mysql root password
  mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_db: mysql
    query: "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ('{{ mysql_root_password }}');"

- name: delete anonymous users
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host_all: yes
    state: absent

- name: remove remote acces
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host: '%'
    state: absent

- name: remove test database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test
    state: absent
