---
# mysql_secure_installation (syntax for mariadb, deb11)

- name: update mysql root password
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    auth_plugin: mysql_native_password
    state: present

- name: delete anonymous users
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host_all: yes
    state: absent

- name: remove remote access
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    host: '%'
    state: absent

- name: remove test database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test
    state: absent
