---
# mysql_secure_installation (syntax for mysql, ubu24)

- name: Set root password for MySQL (if not already set)
  mysql_user:
    name: root
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  when: mysql_root_password != ""

- name: Remove anonymous users
  mysql_user:
    name: ''
    state: absent
    host_all: true

- name: Disable remote root login
  mysql_user:
    name: root
    host: "%"
    state: absent

- name: remove test database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test
    state: absent
