---
- name: Download NodeSource GPG key
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'

- name: Add NodeSource apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_24.x nodistro main"
    state: present
    filename: nodesource
    update_cache: true

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: true

- name: Install Saltcorn via npx
  command: npx saltcorn-install -y
  args:
    creates: /home/saltcorn/.local/bin/saltcorn
  become_user: root

- name: Write saltcorn systemd service file
  template:
    src: saltcorn.service.j2
    dest: /lib/systemd/system/saltcorn.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start saltcorn service
  systemd:
    name: saltcorn
    enabled: true
    state: restarted
    daemon_reload: true

- name: Create user using dynamic credentials
  uri:
    url: "http://172-238-199-65.ip.linodeusercontent.com/auth/create_first_user"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf: "{{ saltcorn_csrf }}"
      default_language: "en"
      email: "{{ soa_email_address }}"
      password: "{{ saltcorn_admin_password }}"
    headers:
      Cookie: "{{ saltcorn_cookie }}"
      Referer: "http://172-238-199-65.ip.linodeusercontent.com/auth/create_first_user"
    status_code: [200, 302]