---
# set_hostname
- name: setting system hostname
  hostname:
    name: "cpanel"

- name: Download cPanel installer
  command: curl -so installer -L https://securedownloads.cpanel.net/latest
  args:
    chdir: /home 

- name: Install the package
  apt:
    name: grub-pc
    state: present

- name: Run the script with flags
  script: /home/installer --skiplicensecheck --skip-cloudlinux >> /var/log/stackscript.log

- name: Remove /etc/cpupdate.conf
  file:
    path: /etc/cpupdate.conf
    state: absent
  
- name: Write .bash_profile
  template:
    src: templates/bashprofile.j2
    dest: /root/.bash_profile

- name: Write motd.sh
  template:
    src: templates/bashprofile.j2
    dest: /etc/motd.sh
  
- name: Create cpinit.done file
  file:
    path: /var/cpanel/cpinit.done
    state: touch