---
# set_hostname
- name: setting system hostname
  hostname:
    name: "cpanel"

- name: Fetch cPanel
  get_url:
    url: https://securedownloads.cpanel.net/latest
    dest: /home/installer
    mode: 0755
    force: yes
    validate_certs: false 

- name: Install the package
  apt:
    name: grub-pc
    state: present

#- name: Run the script with flags failing with "ERROR! [Errno 2] No such file or directory"
#  script: /home/installer --skiplicensecheck --skip-cloudlinux | tee /dev/ttyS0 | tee -a /var/log/stackscript.log
- name: Install cPanel
  command: /bin/bash /home/installer --skiplicensecheck --skip-cloudlinux &
  args:
    chdir: /home

- name: Wait for cPanel to install...
  wait_for:
    path: /var/log/cpanel-install.log
    search_regex: "Thank you for installing cPanel"
    timeout: 3600 # 1 hour

- name: Remove /etc/cpupdate.conf
  file:
    path: /etc/cpupdate.conf
    state: absent 

- name: Write .bash_profile
  template:
    src: templates/bashprofile.j2
    dest: /root/.bash_profile

- name: Write motd.sh
  template:
    src: templates/motd.j2
    dest: /etc/motd.sh

- name: Create cpinit.done file
  file:
    path: /var/cpanel/cpinit.done
    state: touch